sudo: required
services:
  - docker

before-install:
  - docker build -t jidhudocker123/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jidhudocker123/docker-react npm run test
   
